name: Build & Publish Library

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [main]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com
          scope: '@jake-russell'

      - name: Install dependencies
        run: npm ci

      - name: Check for version bump necessity
        id: check
        run: |
          echo "GITHUB_EVENT_NAME=${{ github.event_name }}"

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Workflow triggered by a PR - skipping publish."
            echo "should_publish=false" >> $GITHUB_ENV
            exit 0
          fi

          git fetch origin main

          CHANGED_FILES=$(git diff --name-only origin/main HEAD)
          echo "$CHANGED_FILES" | grep '^src/' && echo "src changed" || echo "src not changed"
          echo "changed_files<<EOF" >> $GITHUB_ENV
          echo "$CHANGED_FILES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

          CHANGED_SRC=$(echo "$CHANGED_FILES" | grep '^src/' || true)

          OLD_VERSION=$(git show origin/main:package.json | jq -r '.version')
          NEW_VERSION=$(jq -r '.version' package.json)

          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"

          if [ -z "$CHANGED_SRC" ]; then
            echo "No changes in src/. Skipping build and publish."
            echo "should_publish=false" >> $GITHUB_ENV
            exit 0
          elif [ "$OLD_VERSION" == "$NEW_VERSION" ]; then
            echo "❌ src/ changed but version was not bumped."
            exit 1
          else
            echo "✅ src/ changed and version was bumped."
            echo "should_publish=true" >> $GITHUB_ENV
          fi

      - name: Build package
        if: env.should_publish == 'true'
        run: npm run build

      - name: Publish to GitHub Packages
        if: env.should_publish == 'true'
        run:
          echo "✅ Publishing..."
          # npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
